---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: quay.io/desource/fedora-build

inputs:
  - name: elasticsearch-src
    path: src

outputs:
  - name: elasticsearch-build
  
run:
  path: ./src/build.sh
